# Site settings
title: The MIT/Wellesley Toons
email: toons-request@mit.edu
description: >
  We're a cross campus a capella group with loads of color :)
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: ToonsACappella

collections:
- members

# Build settings
markdown: kramdown
